title: dixhom.GitHub.io
description: for github webpage
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

# Jekyll tutorial
# http://jmcglone.com/guides/github-pages/
name: Hank Quinlan, Horrible Cop
markdown: kramdown
